"""Turn findings into YAML edits and a PR body.

Only guard-passing DRIFT edits the catalog (the new rate + a price_comments note).
The bot never writes prices_checked: that is the human-verified signal, set by a
reviewer when they confirm and merge. MATCH/UNVERIFIED/URL_STALE/GONE are reported
in the PR body only (no YAML churn), so a pure-MATCH run produces no diff and no PR.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from decimal import Decimal

from prices.prices_types import ModelPrice
from prices.update import ProviderYaml

from .models import Category, Finding


@dataclass(frozen=True)
class DriftEdit:
    provider_id: str
    model_id: str
    field: str
    proposed_rate: Decimal
    note: str


@dataclass
class Report:
    counts: dict[Category, int] = field(default_factory=dict)
    drift_edits: list[DriftEdit] = field(default_factory=list)
    pr_title: str = ''
    pr_body: str = ''

    @property
    def actionable(self) -> bool:
        """A PR is warranted unless every item is MATCH (or there are no items)."""
        return any(c is not Category.MATCH and n for c, n in self.counts.items())


def _drift_note(f: Finding, today: date) -> str:
    src = f.observed_source_rate
    unit = f.observed_source_unit or 'source unit'
    return (
        f'Freshness check on {today.isoformat()} observed {src} per {unit} '
        f'(stored {f.item.field}={f.item.current_rate}, proposed {f.proposed_rate}). '
        f'Verify against {f.item.url} and set prices_checked when confirming.'
    )


def build_report(findings: list[Finding], today: date) -> Report:
    counts: dict[Category, int] = {c: 0 for c in Category}
    edits: list[DriftEdit] = []
    drift_rows: list[str] = []
    check_rows: list[str] = []
    match_rows: list[str] = []

    for f in findings:
        counts[f.category] += 1
        ref = f'{f.item.provider_id}/{f.item.model_id}'
        if f.category is Category.DRIFT and f.proposed_rate is not None:
            edits.append(
                DriftEdit(f.item.provider_id, f.item.model_id, f.item.field, f.proposed_rate, _drift_note(f, today))
            )
            drift_rows.append(
                f'| {ref} | `{f.item.field}` | {f.item.current_rate} | {f.proposed_rate} | '
                f'{f.observed_source_rate} per {f.observed_source_unit} | [source]({f.item.url}) |'
            )
        elif f.category is Category.MATCH:
            match_rows.append(f'| {ref} | {f.item.current_rate} | [source]({f.item.url}) |')
        else:
            check_rows.append(f'| {ref} | {f.category.value} | {f.reason} | [source]({f.item.url}) |')

    body_parts: list[str] = ['# Voice pricing freshness check', '']
    if drift_rows:
        body_parts += [
            '## Proposed rate changes (review against the source before merging)',
            '',
            '| model | field | stored | proposed | observed | source |',
            '| --- | --- | --- | --- | --- | --- |',
            *drift_rows,
            '',
        ]
    if check_rows:
        body_parts += [
            '## Needs a human check (not changed automatically)',
            '',
            '| model | category | reason | source |',
            '| --- | --- | --- | --- |',
            *check_rows,
            '',
        ]
    if match_rows:
        body_parts += [
            '## Verified unchanged',
            '',
            '| model | rate | source |',
            '| --- | --- | --- |',
            *match_rows,
            '',
        ]
    body_parts += [
        '_Generated by the pricing-freshness workflow. The bot does not set `prices_checked`; '
        'set it yourself when you confirm a change. Screenshots are attached as run artifacts._'
    ]

    n_drift = counts[Category.DRIFT]
    n_check = counts[Category.UNVERIFIED] + counts[Category.URL_STALE] + counts[Category.GONE]
    title = f'Pricing freshness: {n_drift} drift, {n_check} to check'

    return Report(counts=counts, drift_edits=edits, pr_title=title, pr_body='\n'.join(body_parts))


def apply_edits(report: Report, providers: dict[str, ProviderYaml]) -> set[str]:
    """Apply DRIFT rate edits to the given provider YAMLs and save them.

    Returns the set of provider ids whose YAML changed. The bot does not touch
    prices_checked; it sets the new rate and a price_comments note.
    """
    changed: set[str] = set()
    for edit in report.drift_edits:
        pyaml = providers[edit.provider_id]
        model = pyaml.provider.find_model(edit.model_id)
        if model is None or not isinstance(model.prices, ModelPrice):
            continue
        new_price = model.prices.model_copy(update={edit.field: edit.proposed_rate})
        updated = model.model_copy(update={'prices': new_price})
        pyaml.update_model(edit.model_id, updated, set_prices=True)
        for m in pyaml.data['models']:
            if m['id'] == edit.model_id:
                m['price_comments'] = edit.note
                break
        changed.add(edit.provider_id)
    for provider_id in changed:
        providers[provider_id].save()
    return changed
